### ISSUE TITLE
Support TypeScript 3.6

### ISSUE THREAD

**Issue by evmar** [angular/tsickle#1065]
Tracking bug for support TypeScript 3.6.

**Comment by evmar** [comment]
If you update tsickle to use TS 3.6, right now a test fails:

```
$ bazel test test:unit_test
[...]
Failures:
1) decorator_downlevel_transformer ctor decorator rewriter includes decorators for primitive type ctor parameters
  Message:
    TypeError: Cannot read property 'kind' of undefined
  Stack:
        at <Jasmine>
        at isParameterPropertyDeclaration (node_modules/typescript/lib/typescript.js:13411:88)
        at Object.filter (node_modules/typescript/lib/typescript.js:469:31)
        at transformClassMembers (node_modules/typescript/lib/typescript.js:70627:20)
        at createClassDeclarationHeadWithoutDecorators (node_modules/typescript/lib/typescript.js:70479:110)
        at visitClassDeclaration (node_modules/typescript/lib/typescript.js:70398:19)
        at visitTypeScript (node_modules/typescript/lib/typescript.js:70246:28)
        at visitorWorker (node_modules/typescript/lib/typescript.js:70041:24)
        at sourceElementVisitorWorker (node_modules/typescript/lib/typescript.js:70066:28)
        at saveStateAndInvoke (node_modules/typescript/lib/typescript.js:69979:27)
        at sourceElementVisitor (node_modules/typescript/lib/typescript.js:70051:20)
        at visitNodes (node_modules/typescript/lib/typescript.js:67563:48)
        at Object.visitLexicalEnvironment (node_modules/typescript/lib/typescript.js:67596:22)
        at visitSourceFile (node_modules/typescript/lib/typescript.js:70335:53)
        at saveStateAndInvoke (node_modules/typescript/lib/typescript.js:69979:27)
        at transformSourceFile (node_modules/typescript/lib/typescript.js:69961:27)
        at transformSourceFileOrBundle (node_modules/typescript/lib/typescript.js:69941:20)
        at transformation (node_modules/typescript/lib/typescript.js:85744:24)
        at transformRoot (node_modules/typescript/lib/typescript.js:85764:82)
        at Object.map (node_modules/typescript/lib/typescript.js:507:29)
        at Object.transformNodes (node_modules/typescript/lib/typescript.js:85751:30)
        at emitJsFileOrBundle (node_modules/typescript/lib/typescript.js:86250:32)
        at emitSourceFileOrBundle (node_modules/typescript/lib/typescript.js:86203:13)
        at forEachEmittedFile (node_modules/typescript/lib/typescript.js:85990:34)
        at Object.emitFiles (node_modules/typescript/lib/typescript.js:86184:9)
        at emitWorker (node_modules/typescript/lib/typescript.js:92134:33)
        at node_modules/typescript/lib/typescript.js:92095:66
        at runWithCancellationToken (node_modules/typescript/lib/typescript.js:92185:24)
        at Object.emit (node_modules/typescript/lib/typescript.js:92095:20)
        at Object.emit (src/tsickle.ts:179:75)
        at translate (test/decorator_downlevel_transformer_test.ts:62:35)
        at expectTranslated (test/decorator_downlevel_transformer_test.ts:78:19)
        at UserContext.fit (test/decorator_downlevel_transformer_test.ts:400:7)
        at <Jasmine>
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
```

I spent some time poking at this.

Our decorator_downlevel_transformer ends up unconditionally transforming every constructor, even if no decorators are involved, by virtue of recreating the parameters object:

```
    function transformConstructor(ctor: ts.ConstructorDeclaration):
        [ts.ConstructorDeclaration, ParameterDecorationInfo[]] {
      [...]
      const updated = ts.updateConstructor(
          ctor, ctor.decorators, ctor.modifiers, newParameters,
          ts.visitFunctionBody(ctor.body, visitor, context));
      return [updated, parametersInfo];
```

When we do so, this clobbers the node's `parent` field, producing the above error.

Meanwhile, `ts.isParameterPropertyDeclaration` pokes at a parent field.

I suspect what happened is that TS 3.6 changed some pass such that it now calls this method without realizing it's not safe.

**Comment by evmar** [comment]
Filed https://github.com/microsoft/TypeScript/issues/33295

**Comment by alfaproject** [comment]
The linked issue is now closed, so I guess this should be fine now?

**Comment by IgorMinar** [comment]
@alfaproject the issue was fixed, but the fix was not released on npm.

**Comment by brad4d** [comment]
The Google internal issue for this is http://b/141179537

**Comment by IgorMinar** [comment]
typescript 3.6.4 was released today

**Comment by IgorMinar** [comment]
friendly ping. can we get a release out and on npm please?
