### ISSUE TITLE
TypeError: ts.isPrivateIdentifier is not a function

### ISSUE THREAD

**Issue by C0ZEN** [angular/tsickle#1138]
When building an Angular library with ng-packagr and without Ivy, the error `TypeError: ts.isPrivateIdentifier is not a function` is thrown

## StackTrace

*terminal*
```
Building Angular Package

------------------------------------------------------------------------------
Building entry point 'ng-homegenius-portal'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
ERROR: ts.isPrivateIdentifier is not a function
An unhandled exception occurred: ts.isPrivateIdentifier is not a function
See "C:\Users\gtest\AppData\Local\Temp\ng-4GXPIH\angular-errors.log" for further details.
```

*angular-errors.log*
```
[error] TypeError: ts.isPrivateIdentifier is not a function
    at visitor (C:\Users\gtest\Documents\homegenius\ng-homegenius-portal\node_modules\tsickle\src\enum_transformer.js:194:55)
    at visitNodes (C:\Users\gtest\Documents\homegenius\ng-homegenius-portal\node_modules\typescript\lib\typescript.js:70998:48)
    at visitLexicalEnvironment (C:\Users\gtest\Documents\homegenius\ng-homegenius-portal\node_modules\typescript\lib\typescript.js:71031:22)
    at Object.visitEachChild (C:\Users\gtest\Documents\homegenius\ng-homegenius-portal\node_modules\typescript\lib\typescript.js:71344:54)
    at visitor (C:\Users\gtest\Documents\homegenius\ng-homegenius-portal\node_modules\tsickle\src\enum_transformer.js:105:31)
    at C:\Users\gtest\Documents\homegenius\ng-homegenius-portal\node_modules\tsickle\src\enum_transformer.js:217:28
    at C:\Users\gtest\Documents\homegenius\ng-homegenius-portal\node_modules\tsickle\src\tsickle.js:294:24
    at transformSourceFileOrBundle (C:\Users\gtest\Documents\homegenius\ng-homegenius-portal\node_modules\typescript\lib\typescript.js:72535:57)
    at transformation (C:\Users\gtest\Documents\homegenius\ng-homegenius-portal\node_modules\typescript\lib\typescript.js:89317:24)
    at transformRoot (C:\Users\gtest\Documents\homegenius\ng-homegenius-portal\node_modules\typescript\lib\typescript.js:89337:82)
```

## TSConfig

```
"compilerOptions": {
    "target": "es2015",
    "module": "es2015",
    "moduleResolution": "node",
    "declaration": true,
    "sourceMap": true,
    "inlineSources": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "downlevelIteration": true,
    "importHelpers": true,
    "lib": [
      "dom",
      "es2018"
    ],
    "types": [
      "jasmine",
      "jasminewd2",
      "node"
    ],
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "plugins": [
      {
        "name": "@angular/language-service"
      }
    ]
  },
  "angularCompilerOptions": {
    "skipTemplateCodegen": true,
    "enableResourceInlining": true,
    "enableIvy": false,
    "annotateForClosureCompiler": true,
    "skipMetadataEmit": false,
    "strictMetadataEmit": true,
    "strictInjectionParameters": true,
    "generateCodeForLibraries": true,
    "fullTemplateTypeCheck": true,
    "trace": true,
    "strictTemplates": true,
    "strictInputTypes": true
  }
```

## Environment

```
"@angular/core": "~9.0.5"
"tsickle": "~0.38.1"
"ng-packagr": "~9.0.2"
```

**Comment by mprobst** [comment]
This means your TypeScript is 3.7 or earlier, `ts.isPrivateIdentifier` is new in TypeScript 3.8+.

tsickle moved to TypeScript 3.8 in version 0.38.1. If you want to use TypeScript 3.7 or earlier, you'll need to use tsickle 0.38.0 or earlier.

Also, this means some software in your dependencies doesn't properly specify a version dependency on tsickle (ng-packagr maybe?).

**Comment by C0ZEN** [comment]
Thank you @mprobst for this information.

By the way, why is there no changelog in this project?

**Comment by mprobst** [comment]
Because that's work ;-)

The commit messages are a good approximation I hope.

**Comment by KheireddineAzzez** [comment]
I ran into the same error today. You should downgrade your typescript dependency to 3.9.7. That fixed it for me.    
  
npm install typescript@">=3.0.0 <3.9.7"
