### ISSUE TITLE
can't compile angular with tsickle 0.1.4

### ISSUE THREAD

**Issue by alexeagle** [angular/tsickle#151]
I added a bit of debug info. We blow up here:
https://github.com/angular/angular/blob/7aa1790874b76db122a93316d9324029f766c9f3/modules/%40angular/common/src/pipes/async_pipe.ts#L81

when attempting to `this.typeChecker.getTypeAtLocation(param.type)` of the `ChangeDetectorRef`-typed parameter. 

```
get type of  NodeObject {
  kind: 141,
  pos: 2749,
  end: 2772,
  flags: 0,
  parent:
   NodeObject {
     kind: 147,
     pos: 2733,
     end: 2795,
     flags: 0,
     parent:
      NodeObject {
        kind: 220,
        pos: 1281,
        end: 4497,
        flags: 1,
        parent: [Object],
        decorators: [Object],
        modifiers: [Object],
        name: [Object],
        typeParameters: undefined,
        heritageClauses: [Object],
        members: [Object],
        _children: [Object] },
     decorators: undefined,
     typeParameters: undefined,
     parameters: [ [Circular], pos: 2749, end: 2772 ],
     body:
      NodeObject {
        kind: 198,
        pos: 2773,
        end: 2795,
        flags: 0,
        parent: [Circular],
        statements: [Object] } },
  decorators: undefined,
  dotDotDotToken: undefined,
  name:
   NodeObject {
     kind: 69,
     pos: 2749,
     end: 2753,
     flags: 0,
     parent: [Circular],
     text: '_ref' },
  questionToken: undefined,
  type:
   NodeObject {
     kind: 154,
     pos: 2754,
     end: 2772,
     flags: 0,
     parent: [Circular],
     typeName:
      NodeObject {
        kind: 69,
        pos: 2754,
        end: 2772,
        flags: 0,
        parent: [Circular],
        text: 'ChangeDetectorRef' } },
  initializer: undefined }
Unable to convert  /Users/alexeagle/Projects/angular/modules/@angular/common/src/pipes/async_pipe.ts
TypeError: Cannot read property 'members' of undefined
    at resolveName (/Users/alexeagle/Projects/angular/node_modules/typescript/lib/typescript.js:15593:73)
    at resolveEntityName (/Users/alexeagle/Projects/angular/node_modules/typescript/lib/typescript.js:16013:26)
    at getTypeFromTypeReference (/Users/alexeagle/Projects/angular/node_modules/typescript/lib/typescript.js:19262:54)
    at getTypeFromTypeNode (/Users/alexeagle/Projects/angular/node_modules/typescript/lib/typescript.js:19594:28)
    at Object.getTypeOfNode [as getTypeAtLocation] (/Users/alexeagle/Projects/angular/node_modules/typescript/lib/typescript.js:29896:24)
    at ClassRewriter.gatherConstructor (/Users/alexeagle/Projects/angular/node_modules/tsickle/build/src/decorator-annotator.js:63:44)
    at ClassRewriter.maybeProcess (/Users/alexeagle/Projects/angular/node_modules/tsickle/build/src/decorator-annotator.js:112:22)
    at ClassRewriter.Rewriter.visit (/Users/alexeagle/Projects/angular/node_modules/tsickle/build/src/rewriter.js:32:19)
    at ClassRewriter.Rewriter.writeNode (/Users/alexeagle/Projects/angular/node_modules/tsickle/build/src/rewriter.js:64:18)
    at ClassRewriter.Rewriter.visit (/Users/alexeagle/Projects/angular/node_modules/tsickle/build/src/rewriter.js:33:18)
Compilation failed
```

fyi @martine

**Comment by martine** [comment]
The stacktrace points at this:

```js
        let sym = this.typeChecker.getTypeAtLocation(param.type).getSymbol();
```

Maybe try getTypeAtLocation on `param.name` instead?

**Comment by alexeagle** [comment]
`getTypeAtLocation(param.name)` returns undefined.

I thought that the different typescript version was the likely problem, but upgrading typescript@1.9.0-dev.20160409 I still can't reproduce this issue in tsickle's unit test.

**Comment by martine** [comment]
https://github.com/Microsoft/TypeScript/issues/8136 seems like the same stack.  Regardless of using the API right, mhegazy observes that it shouldn't crash.

**Comment by alexeagle** [comment]
I agree, there's surely a repro for this we could add in TS *somewhere* but it would be daunting to find the right spot...

Interesting that it can repro with 1.8 and 1.9-dev

**Comment by alexeagle** [comment]
oops, that fix broke the build, trying again...

**Comment by alexeagle** [comment]
after great debugging, this turned out to be simple: the source file being passed to tsickle wasn't type-checked so it had no symbol table references. Was a bug in my tsickle update PR.
Thanks @martine...

**Comment by mprobst** [comment]
Oh dear. Well, good that we finally figured it out.

**Comment by vicb** [comment]
:+1:
