### ISSUE TITLE
tsickle crashes due to source map composition not finding a source map

### ISSUE THREAD

**Issue by mprobst** [angular/tsickle#399]
This issue was worked around in 6f14360b39dbbbf6643fd7f321a204dfc3aae355, which was reverted by @LucasSloan in 8a341a9c7fa2dce27aa37864386da75286a7f985.

Lucas, could you confirm that this is finally fixed at head now (maybe in #392 or #390 - I cannot tell from the PR descriptions)?

For reference, this was the failure stack trace, which seemed to be caused by a code path not correctly checking for presence of a source map:

```
Compilation failed TypeError: Cannot read property '1' of null
   at Object.extractInlineSourceMap (tsickle/source_map_utils.js:32:42)
   at TsickleCompilerHost.combineInlineSourceMaps (tsickle/tsickle_compiler_host.js:152:44)
   at TsickleCompilerHost.writeFile (tsickle/tsickle_compiler_host.js:79:32)
   at Object.writeFile (typescript/v2_1_5/lib/typescript.js:62935:132)
   at Object.writeFile (typescript/v2_1_5/lib/typescript.js:8930:14)
   at printFile (typescript/v2_1_5/lib/typescript.js:60024:16)
   at emitFile (typescript/v2_1_5/lib/typescript.js:59973:21)
   at onSingleFileEmit (typescript/v2_1_5/lib/typescript.js:8838:13)
   at Object.forEachTransformedEmitFile (typescript/v2_1_5/lib/typescript.js:8815:21)
```

**Comment by LucasSloan** [comment]
Fixed by #390
