### ISSUE TITLE
Cannot read property 'toJSON' of undefined

### ISSUE THREAD

**Issue by jrgleason** [angular/tsickle#453]
I have a [project here](https://github.com/jrgleason/flex-layout/tree/UPGRADE) that uses ngc. However, when I compile the project using TS 2.2.2 and the command `./node_modules/.bin/ngc -p src/lib/tsconfig.json` I get the following error...

```
TypeError: Cannot read property 'toJSON' of undefined
    at Object.sourceMapGeneratorToConsumer (.../node_modules/tsickle/build/src/source_map_utils.js:65:42)
    at TsickleCompilerHost.combineSourceMaps (.../flex-layout/node_modules/tsickle/build/src/tsickle_compiler_host.js:167:74)
    at TsickleCompilerHost.writeFile (.../flex-layout/node_modules/tsickle/build/src/tsickle_compiler_host.js:111:28)
    at Object.writeFile (.../flex-layout/node_modules/typescript/lib/typescript.js:64240:132)
    at Object.writeFile (.../flex-layout/node_modules/typescript/lib/typescript.js:9020:14)
    at printSourceFileOrBundle (.../flex-layout/node_modules/typescript/lib/typescript.js:61197:20)
    at emitSourceFileOrBundle (.../flex-layout/node_modules/typescript/lib/typescript.js:61155:21)
    at Object.forEachEmittedFile (.../flex-layout/node_modules/typescript/lib/typescript.js:8986:17)
    at Object.emitFiles (.../flex-layout/node_modules/typescript/lib/typescript.js:61137:12)
    at emitWorker (.../flex-layout/node_modules/typescript/lib/typescript.js:64294:33)
```

I would expect that this is probably related to using TS 2.2

https://github.com/angular/tsickle/pull/447

**Comment by jrgleason** [comment]
I tried downgrading to 2.1.5 per the latest angular and now I get...

```
TypeError: Cannot read property 'file' of undefined
    at SourceMapGenerator_applySourceMap [as applySourceMap] (.../flex-layout/node_modules/source-map/lib/source-map-generator.js:176:29)
    at TsickleCompilerHost.combineSourceMaps (.../flex-layout/node_modules/tsickle/build/src/tsickle_compiler_host.js:168:39)
    at TsickleCompilerHost.writeFile (.../flex-layout/node_modules/tsickle/build/src/tsickle_compiler_host.js:111:28)
    at Object.writeFile (.../flex-layout/node_modules/typescript/lib/typescript.js:64240:132)
    at Object.writeFile (.../flex-layout/node_modules/typescript/lib/typescript.js:9020:14)
    at printSourceFileOrBundle (.../flex-layout/node_modules/typescript/lib/typescript.js:61197:20)
    at emitSourceFileOrBundle (.../flex-layout/node_modules/typescript/lib/typescript.js:61155:21)
    at Object.forEachEmittedFile (.../flex-layout/node_modules/typescript/lib/typescript.js:8986:17)
    at Object.emitFiles (.../flex-layout/node_modules/typescript/lib/typescript.js:61137:12)
    at emitWorker (.../flex-layout/node_modules/typescript/lib/typescript.js:64294:33)
``

**Comment by jrgleason** [comment]
I could fix the second issue by removing this if (which looks right given the TODO)...

tsickle_compiler_host.js

:169

```
if (false) {// this.decoratorDownlevelSourceMaps.size > 0) {
            // TODO(lucassloan): remove when the .d.ts has the correct types
            for (var _b = 0, _c = tscSourceMapConsumer.sources; _b < _c.length; _b++) {
                var sourceFileName = _c[_b];
                var sourceMapKey = this.getSourceMapKeyForPathAndName(filePath, sourceFileName);
                var decoratorDownlevelSourceMapGenerator = this.decoratorDownlevelSourceMaps.get(sourceMapKey);
                var decoratorDownlevelSourceMapConsumer = sourceMapUtils.sourceMapGeneratorToConsumer(decoratorDownlevelSourceMapGenerator, sourceFileName, sourceFileName);
                tscSourceMapGenerator.applySourceMap(decoratorDownlevelSourceMapConsumer);
            }
        }
```

**Comment by jrgleason** [comment]
Any word on this? I can issue a pull request if others think this is ok

**Comment by ThomasBurleson** [comment]
@hansl - any thoughts ?

**Comment by hansl** [comment]
Not sure why me, I never worked on tsickle. It seems to be in their source map generation where a source map hasn't been created. Do you have source maps for that file?

**Comment by ThomasBurleson** [comment]
@LucasSloan - here is a link to the latest [@angular/flex-layout builds](https://github.com/angular/flex-layout-builds): with sourcemaps. 

> Here is the link to the originating issue and PR:
*  https://github.com/angular/flex-layout/pull/238
*  https://github.com/angular/flex-layout/issues/236

**Comment by LucasSloan** [comment]
@jrgleason Removing that if block isn't the right solution, that comment refers to a type annotation not present in the compiled js code.  I'll take a look.

**Comment by LucasSloan** [comment]
@jrgleason @ThomasBurleson It looks like the issue is that you specify a maproot of "" in your tsconfig.  Can you remove that setting?

**Comment by ThomasBurleson** [comment]
Fyi @devversion

**Comment by jrgleason** [comment]
@LucasSloan this is my tsconfig I don't see maproot...

{
  "compilerOptions": {
    "target": "es5",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "jsx": "react",
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "lib": [
      "es2016",
      "dom"
    ]
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}

**Comment by LucasSloan** [comment]
@jrgleason The tsconfig in your original comment [src/lib/tsconfig.json](https://github.com/jrgleason/flex-layout/blob/UPGRADE/src/lib/tsconfig.json) has one:

{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "declaration": true,
    "inlineSources": true,
    "skipDefaultLibCheck": true,
    "noImplicitAny": false,
    "noImplicitReturns": true,
    "suppressImplicitAnyIndexErrors": true,
    "stripInternal": false,
    **"mapRoot": "",**
    "rootDir": ".",
    "sourceMap": true,
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "lib": ["es6", "es2015", "dom"],
    "outDir": "../../dist/@angular/flex-layout",
    "typeRoots": [
      "../../node_modules/@types"
    ]
  },
  "exclude": [
    "**/*.spec.*",
    "utils/testing/custom-matchers.ts",
    "utils/testing/helpers.ts",
    "system-config-spec.ts",
    "tsconfig-demo-app."
  ],
  "angularCompilerOptions": {
    "genDir": "../../dist/aot/@angular/flex-layout",
    "debug": true
  }
}

**Comment by gonzofish** [comment]
@LucasSloan that suggestion worked for my case--thanks a lot!

**Comment by mprobst** [comment]
@LucasSloan should our code be a bit more conservative somewhere, possibly report a better error rather than crashing?

**Comment by jcarloslr10** [comment]
I'm trying to compile in AOT mode but I have the same issue. This is my tsconfig.json:

{
  "compilerOptions": {
    "baseUrl": "dist",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es6", "dom" ],
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/js",
    "sourceMap": false,
    "target": "es5",
    "types": [
      "node",
      "jasmine"
    ],
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
  "exclude": [
    "main.aot.ts",
    "test",
    "e2e",
    "node_modules"
  ],
  "angularCompilerOptions": {
    "entryModule": "app/app.module#AppModule",
    "genDir": "./aot"
  }
}

and this is my error:

TypeError: Cannot read property 'toJSON' of undefined
    at Object.sourceMapGeneratorToConsumer (C:\Users\...\node_modules\tsickle\build\src\source_map_utils.js:65:42)
    at TsickleCompilerHost.combineSourceMaps (C:\Users\...\node_modules\tsickle\build\src\tsickle_compiler_host.js:167:74)
    at TsickleCompilerHost.writeFile (C:\Users\...\node_modules\tsickle\build\src\tsickle_compiler_host.js:111:28)
....

@LucasSloan, what possible solution exists? It only worked me the @jrgleason solution which is to remove the if statement, but I don't think it's the best choice.

Thx!!

**Comment by HenryZhang-Infotrack** [comment]
Remove "mapRoot" and it works. thanks. mate

**Comment by alan-agius4** [comment]
Any update regarding this please? it's been open for ages, and I do need to specify `mapRoot` in my case

**Comment by evmar** [comment]
This sounds like a bug in ngc.
