### ISSUE TITLE
TypeError: base64 is not a function

### ISSUE THREAD

**Issue by sam-s4s** [angular/tsickle#457]
I'm trying to do an AoT build of angular (using ngc), and am getting the following error...

```
TypeError: base64 is not a function
    at Function.from (native)
    at Function.from (native)
    at Object.extractInlineSourceMap (C:\s4s\src\web\billing\node_modules\tsickle\build\src\source_map_utils.js:33:19)
    at TsickleCompilerHost.stripAndStoreExistingSourceMap (C:\s4s\src\web\billing\node_modules\tsickle\build\src\tsickle_compiler_host.js:128:48)
    at TsickleCompilerHost.getSourceFile (C:\s4s\src\web\billing\node_modules\tsickle\build\src\tsickle_compiler_host.js:89:25)
    at findSourceFile (C:\s4s\src\web\billing\node_modules\typescript\lib\typescript.js:64751:29)
    at processImportedModules (C:\s4s\src\web\billing\node_modules\typescript\lib\typescript.js:64898:25)
    at findSourceFile (C:\s4s\src\web\billing\node_modules\typescript\lib\typescript.js:64779:17)
    at processSourceFile (C:\s4s\src\web\billing\node_modules\typescript\lib\typescript.js:64682:27)
    at processRootFile (C:\s4s\src\web\billing\node_modules\typescript\lib\typescript.js:64570:13)
Compilation failed
```

Function in question (error on last line)...
```
export function extractInlineSourceMap(source: string): string {
  const inlineSourceMapRegex = getInlineSourceMapRegex();
  let previousResult: RegExpExecArray|null = null;
  let result: RegExpExecArray|null = null;
  // We want to extract the last source map in the source file
  // since that's probably the most recent one added.  We keep
  // matching against the source until we don't get a result,
  // then we use the previous result.
  do {
    previousResult = result;
    result = inlineSourceMapRegex.exec(source);
  } while (result !== null);
  const base64EncodedMap = previousResult![1];
  return Buffer.from(base64EncodedMap, 'base64').toString('utf8');
}
```

Anyone know what's happening?

**Comment by mprobst** [comment]
What's your node version? It might be too old.

**Comment by sam-s4s** [comment]
:'( it totally was. I just figured this out LOL good timing

Apologies! Didn't know there was a requirement for a newer version.

**Comment by mprobst** [comment]
Good to hear you fixed it.
