### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by DcsMarcRemolt** [angular/tsickle#473]
Trying to compile a rather large project with @angular/compiler results in multiple places where this error is thrown:

```
TypeError: Cannot read property 'length' of undefined
    at ClassRewriter.shouldLower (/Users/xxx/workspace/project-x/node_modules/tsickle/build/src/decorator-annotator.js:38:106)
    at /Users/xxx/workspace/project-x/node_modules/tsickle/build/src/decorator-annotator.js:75:68
    at Array.filter (native)
    at ClassRewriter.decoratorsToLower (/Users/xxx/workspace/project-x/node_modules/tsickle/build/src/decorator-annotator.js:75:33)
    at ClassRewriter.gatherMethodOrProperty (/Users/xxx/workspace/project-x/node_modules/tsickle/build/src/decorator-annotator.js:160:31)
    at ClassRewriter.maybeProcess (/Users/xxx/workspace/project-x/node_modules/tsickle/build/src/decorator-annotator.js:187:22)
    at ClassRewriter.Rewriter.visit (/Users/xxx/workspace/project-x/node_modules/tsickle/build/src/rewriter.js:52:19)
    at /Users/xxx/workspace/project-x/node_modules/tsickle/build/src/decorator-annotator.js:96:19
    at visitEachNode (/Users/xxx/workspace/project-x/node_modules/typescript/lib/typescript.js:14674:30)
    at Object.forEachChild (/Users/xxx/workspace/project-x/node_modules/typescript/lib/typescript.js:14921:21)
```

It seems getDecoratorDeclarations can return undefined under certain circumstances which the for of loop does not like, as this gets compiled down to a for loop with x.length to check the number of iterations.

**Comment by evmar** [comment]
This should be filed against @angular/compiler.
