### ISSUE TITLE
Static methods are incorrectly transpiled to be instance methods.

### ISSUE THREAD

**Issue by tadeegan** [angular/tsickle#475]
tsc -v = 2.2.2
tsickle@0.21.6

```
// input.d.ts
declare module A {
    class B {
        private static staticMethod(): any;
    }
}
```

```
// output.externs.js
/**
 * @externs
 * @suppress {duplicate}
 */
// NOTE: generated by tsickle, do not edit.
// externs from example.d.ts:
/** @const */
var A = {};

/** @constructor @struct */
A.B = function() {};

/**
 * @return {?}
 */
A.B.prototype.staticMethod = function() {};

```

**Comment by tadeegan** [comment]
Seems very obvious but I'm guessing the issue is here:
https://github.com/angular/tsickle/blob/master/src/tsickle.ts#L1451

**Comment by evmar** [comment]
Yeah that looks about right, wanna write a patch?

(Our externs generation is pretty weak.  Is it possible that nobody has yet used a d.ts file with "static" in it?  Because JS has no 'static' I imagine d.ts files might use a different way of expressing this, like an interface describing the class itself.)

**Comment by tadeegan** [comment]
I'm trying to add a test but the `export UPDATE_GOLDENS=1` doesn't seem to regen the externs.js file. Any ideas? Is that manual?

**Comment by tadeegan** [comment]
Tried generating the externs file manually but see:

```
> node build/src/main.js test_files/declare/declare-module.d.ts test_files/declare/declare.d.ts --externs=test_files/declare/externs.js
Error at /Users/tdeegan/dev/tsickle/node_modules/@types/node/index.d.ts:49:13: Subsequent variable declarations must have the same type.  Variable 'global' must be of type 'any', but here has type 'Global'.
Error at /Users/tdeegan/dev/tsickle/test_files/declare/declare.d.ts:63:3: 'myMethod', which lacks return-type annotation, implicitly has an 'any' return type.
Error at /Users/tdeegan/dev/tsickle/test_files/declare/declare.d.ts:91:18: 'usesArguments', which lacks return-type annotation, implicitly has an 'any' return type.
Error at /Users/tdeegan/dev/tsickle/test_files/declare/declare.d.ts:94:18: 'destructures', which lacks return-type annotation, implicitly has an 'any' return type.
Error at /Users/tdeegan/dev/tsickle/test_files/declare/declare.d.ts:94:35: Binding element 'number' implicitly has an 'any' type.
```

**Comment by evmar** [comment]
```sh
sigint:~/projects/tsickle$ echo 'declare var foo;' >> test_files/declare/declare.d.ts 
sigint:~/projects/tsickle$ UPDATE_GOLDENS=1  ./node_modules/.bin/gulp test
[...]
sigint:~/projects/tsickle$ git st
 M test_files/declare/declare.d.ts
 M test_files/declare/declare.tsickle.d.ts
 M test_files/declare/externs.js
```

Not sure what's going wrong for you.
