### ISSUE TITLE
Tests fail [base64 is not a function]

### ISSUE THREAD

**Issue by tadeegan** [angular/tsickle#476]
When I run 'gulp test', I see:

 ```
 1) source maps composes inline sources:
     TypeError: base64 is not a function
      at Function.from (native)
      at Function.from (native)
      at Object.extractInlineSourceMap (src/source_map_utils.ts:34:17)
      at TsickleCompilerHost.combineInlineSourceMaps (src/tsickle_compiler_host.ts:273:42)
      at TsickleCompilerHost.writeFile (src/tsickle_compiler_host.ts:178:24)
      at Object.writeFile (node_modules/typescript/lib/typescript.js:66869:132)
      at Object.writeFile (node_modules/typescript/lib/typescript.js:9048:14)
      at printSourceFileOrBundle (node_modules/typescript/lib/typescript.js:63763:16)
      at emitSourceFileOrBundle (node_modules/typescript/lib/typescript.js:63714:21)
      at Object.forEachEmittedFile (node_modules/typescript/lib/typescript.js:9005:17)

  2) source maps doesn't blow up trying to handle a source map in a .d.ts file:
     TypeError: base64 is not a function
      at Function.from (native)
      at Function.from (native)
      at Object.extractInlineSourceMap (src/source_map_utils.ts:34:17)
      at TsickleCompilerHost.combineInlineSourceMaps (src/tsickle_compiler_host.ts:273:42)
      at TsickleCompilerHost.writeFile (src/tsickle_compiler_host.ts:178:24)
      at Object.writeFile (node_modules/typescript/lib/typescript.js:66869:132)
      at Object.writeFile (node_modules/typescript/lib/typescript.js:9048:14)
      at printSourceFileOrBundle (node_modules/typescript/lib/typescript.js:63763:16)
      at emitSourceFileOrBundle (node_modules/typescript/lib/typescript.js:63714:21)
      at Object.forEachEmittedFile (node_modules/typescript/lib/typescript.js:9005:17)

  3) source maps handles input source maps:
     TypeError: utf8 is not a function
      at Function.from (native)
      at Function.from (native)
      at Object.setInlineSourceMap (src/source_map_utils.ts:46:35)
      at decoratorDownlevelAndAddInlineSourceMaps (/Users/tdeegan/dev/test/e2e_source_map_test.ts:314:38)
      at Context.<anonymous> (/Users/tdeegan/dev/test/e2e_source_map_test.ts:235:30)

  4) source maps handles input source maps with different file names than supplied to tsc:
     TypeError: utf8 is not a function
      at Function.from (native)
      at Function.from (native)
      at Context.<anonymous> (/Users/tdeegan/dev/test/e2e_source_map_test.ts:249:37)

  5) source maps doesn't blow up putting an inline source map in an empty file:
     TypeError: base64 is not a function
      at Function.from (native)
      at Function.from (native)
      at Object.extractInlineSourceMap (src/source_map_utils.ts:34:17)
      at TsickleCompilerHost.combineInlineSourceMaps (src/tsickle_compiler_host.ts:273:42)
      at TsickleCompilerHost.writeFile (src/tsickle_compiler_host.ts:178:24)
      at Object.writeFile (node_modules/typescript/lib/typescript.js:66869:132)
      at Object.writeFile (node_modules/typescript/lib/typescript.js:9048:14)
      at printSourceFileOrBundle (node_modules/typescript/lib/typescript.js:63763:16)
      at emitSourceFileOrBundle (node_modules/typescript/lib/typescript.js:63714:21)
      at Object.forEachEmittedFile (node_modules/typescript/lib/typescript.js:9005:17)

  6) source maps handles mixed source mapped and non source mapped input:
     TypeError: utf8 is not a function
      at Function.from (native)
      at Function.from (native)
      at Object.setInlineSourceMap (src/source_map_utils.ts:46:35)
      at decoratorDownlevelAndAddInlineSourceMaps (/Users/tdeegan/dev/test/e2e_source_map_test.ts:314:38)
      at Context.<anonymous> (/Users/tdeegan/dev/test/e2e_source_map_test.ts:282:30)

```

tsickle git:(master) ✗ node -v
v5.0.0

**Comment by tadeegan** [comment]
Seems to have been related to my node version although other places on the internet said version 5 should work.

Run properly with v7.9.0

Perhaps you should add the "engines" tag to the package.json that requires a specific node version?

**Comment by evmar** [comment]
Can you send a PR with a proper 'engines' tag?
