### ISSUE TITLE
transformer produces bad output for shebang line

### ISSUE THREAD

**Issue by alexeagle** [angular/tsickle#581]
fringe corner case.

https://github.com/angular/angular/blob/d2c0d986d44f3a7a29bdeacbe973a5550f5c6839/packages/compiler-cli/src/extract_i18n.ts#L1
starts with 
`#!/usr/bin/env node`

tsickle transform interprets this as a regular expression literal and produces bad AST:
```
Compilation failed Error: Debug Failure. False expression: Literal kind '12' not accounted for in /usr/local/google/_blaze_alexeagle/e1bbf61e81d08d074a7ec0cac497db1f/blaze-workers/worker-10-TypeScriptCompile/third_party/javascript/angular2/rc/packages/compiler-cli/src/extract_i18n.ts
    at Object.assert (/tmp/sar.tsc_released.sar.88197.iULipURYvk/tsc_released.runfiles/google3/third_party/javascript/node_modules/typescript/v2_3_4/lib/typescript.js:3329:23)
    at Object.fail (/tmp/sar.tsc_released.sar.88197.iULipURYvk/tsc_released.runfiles/google3/third_party/javascript/node_modules/typescript/v2_3_4/lib/typescript.js:3334:19)
    at Object.getLiteralText (/tmp/sar.tsc_released.sar.88197.iULipURYvk/tsc_released.runfiles/google3/third_party/javascript/node_modules/typescript/v2_3_4/lib/typescript.js:6872:18)
    at getLiteralTextOfNode (/tmp/sar.tsc_released.sar.88197.iULipURYvk/tsc_released.runfiles/google3/third_party/javascript/node_modules/typescript/v2_3_4/lib/typescript.js:66404:23)
    at emitLiteral (/tmp/sar.tsc_released.sar.88197.iULipURYvk/tsc_released.runfiles/google3/third_party/javascript/node_modules/typescript/v2_3_4/lib/typescript.js:64790:24)
    at pipelineEmitExpression (/tmp/sar.tsc_released.sar.88197.iULipURYvk/tsc_released.runfiles/google3/third_party/javascript/node_modules/typescript/v2_3_4/lib/typescript.js:64691:28)
    at pipelineEmitWithHint (/tmp/sar.tsc_released.sar.88197.iULipURYvk/tsc_released.runfiles/google3/third_party/javascript/node_modules/typescript/v2_3_4/lib/typescript.js:64442:49)
    at emitNodeWithSourceMap (/tmp/sar.tsc_released.sar.88197.iULipURYvk/tsc_released.runfiles/google3/third_party/javascript/node_modules/typescript/v2_3_4/lib/typescript.js:61931:21)
    at pipelineEmitWithSourceMap (/tmp/sar.tsc_released.sar.88197.iULipURYvk/tsc_released.runfiles/google3/third_party/javascript/node_modules/typescript/v2_3_4/lib/typescript.js:64432:17)
    at emitNodeWithNestedComments (/tmp/sar.tsc_released.sar.88197.iULipURYvk/tsc_released.runfiles/google3/third_party/javascript/node_modules/typescript/v2_3_4/lib/typescript.js:62214:17)
```

**Comment by evmar** [comment]
Fixed.
