### ISSUE TITLE
golden file test output hard to read

### ISSUE THREAD

**Issue by mprobst** [angular/tsickle#631]
Failures in the golden files now print like this:

```
Failures:
1) golden tests with transformer import_equals
  Message:
    AssertionError: test_files/import_equals/externs.js: expected '/**\n * @externs\n * @suppress {duplicate,checkTypes}\n */\n// NOTE: generated by tsickle, do not edit.\n/** @const */\nvar __React = {};\n/**\n * @constructor\n * @struct\n */\n__React.X = function() {};\n/** @const */ var React = __React;\n' to equal '/**\n * @externs\n * @suppress {duplicate,checkTypes}\n */\n// NOTE: generated by tsickle, do not edit.\n/** @const */\nvar __React = {};\n/**\n * @constructor\n * @struct\n */\n__React.X = function() {};\n\n/* TODO: ImportEqualsDeclaration in  */\n'
  Stack:
    AssertionError: test_files/import_equals/externs.js: expected '/**\n * @externs\n * @suppress {duplicate,checkTypes}\n */\n// NOTE: generated by tsickle, do not edit.\n/** @const */\nvar __React = {};\n/**\n * @constructor\n * @struct\n */\n__React.X = function() {};\n/** @const */ var React = __React;\n' to equal '/**\n * @externs\n * @suppress {duplicate,checkTypes}\n */\n// NOTE: generated by tsickle, do not edit.\n/** @const */\nvar __React = {};\n/**\n * @constructor\n * @struct\n */\n__React.X = function() {};\n\n/* TODO: ImportEqualsDeclaration in  */\n'
        at compareAgainstGolden (/private/var/tmp/_bazel_martinprobst/b50d5b890249591e47db69431e34e5fb/execroot/io_angular_tsickle/bazel-out/darwin_x86_64-fastbuild/bin/test/golden_tsickle_test.js:135:34)
        at UserContext.<anonymous> (/private/var/tmp/_bazel_martinprobst/b50d5b890249591e47db69431e34e5fb/execroot/io_angular_tsickle/bazel-out/darwin_x86_64-fastbuild/bin/test/golden_tsickle_test.js:269:13)
```

We used to have a somewhat reasonable diff printed. Can we fix that? It makes iterating on these tests unnecessarily hard.

**Comment by mprobst** [comment]
I've since fixed this myself.
