### ISSUE TITLE
Crash when class extends <expression>

### ISSUE THREAD

**Issue by aomarks** [angular/tsickle#679]
tsickle crashes if the RHS of a `class extends` is an expression instead of a symbol. This pattern is useful when declaring classes built up using class mixin functions as described here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html

```ts
declare function MyMixin<T extends new (...args: any[]) => {}>(base: T):
    T & MixinConstructor;

interface MixinConstructor {
  new(...args: any[]): MyMixin;
}

interface MyMixin {
  mixinProp: string;
}

declare class MyClass extends MyMixin(HTMLElement) {
  classProp: string;
}
```

```
$ tsickle --externs=tsickle.js
Warning at mixin.d.ts: unhandled type flags: Intersection
/Users/aomarks/.nvm/versions/node/v9.0.0/lib/node_modules/tsickle/src/tsickle.js:1700
                        finally { if (e_18) throw e_18.error; }
                                            ^

Error: no symbol
    at ExternsWriter.ClosureRewriter.mustGetSymbolAtLocation (/Users/aomarks/.nvm/versions/node/v9.0.0/lib/node_modules/tsickle/src/tsickle.js:202:23)
    at ExternsWriter.ClosureRewriter.maybeAddHeritageClauses (/Users/aomarks/.nvm/versions/node/v9.0.0/lib/node_modules/tsickle/src/tsickle.js:488:44)
    at ExternsWriter.writeExternsType (/Users/aomarks/.nvm/versions/node/v9.0.0/lib/node_modules/tsickle/src/tsickle.js:1861:22)
    at ExternsWriter.visit (/Users/aomarks/.nvm/versions/node/v9.0.0/lib/node_modules/tsickle/src/tsickle.js:1788:26)
    at ExternsWriter.visit (/Users/aomarks/.nvm/versions/node/v9.0.0/lib/node_modules/tsickle/src/tsickle.js:1692:34)
    at /Users/aomarks/.nvm/versions/node/v9.0.0/lib/node_modules/tsickle/src/tsickle.js:1669:75
    at Array.forEach (<anonymous>)
    at ExternsWriter.process (/Users/aomarks/.nvm/versions/node/v9.0.0/lib/node_modules/tsickle/src/tsickle.js:1669:36)
    at writeExterns (/Users/aomarks/.nvm/versions/node/v9.0.0/lib/node_modules/tsickle/src/tsickle.js:2071:59)
    at /Users/aomarks/.nvm/versions/node/v9.0.0/lib/node_modules/tsickle/src/tsickle.js:2184:26```

**Comment by evmar** [comment]
Do you have any thoughts on what closure JS we should emit in this case?
