### ISSUE TITLE
unclear how to build and run tsickle binary

### ISSUE THREAD

**Issue by aomarks** [angular/tsickle#723]
The README does not explain how to build and run tsickle, and I haven't been able to work it out yet.

Here's what I tried:

```sh
$ git clone git@github.com:angular/tsickle.git
$ cd tsickle
$ bazel run @yarn//:yarn --script_path=yarn_install.sh && ./yarn_install.sh
$ npm run build
$ node built/src/main.js
```

But this throws:

```
module.js:540
    throw err;
    ^

Error: Cannot find module 'tsickle/src/typescript'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at /Users/aomarks/git/tsickle/built/src/main.js:27:14
    at Object.defineProperty.value (/Users/aomarks/git/tsickle/built/src/main.js:14:17)
    at Object.<anonymous> (/Users/aomarks/git/tsickle/built/src/main.js:20:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
```

I also tried `bazel build src` instead of the npm script, but got the same error.

`bazel test:unit_test` does work for me, so I guess things are generally set up ok.

macOS 10.13.2
node v8.9.4
bazel 0.9.0-homebrew

**Comment by pcj** [comment]
Still a valid comment, there is no `_binary` rule here that one can run `tsickle`, did I miss it?

`yarn global add tsickle` works thought.

**Comment by mprobst** [comment]
See https://github.com/angular/tsickle#usage.
