### ISSUE TITLE
Tsickle incorrectly generates common.js format`exports.MyType = ...;` rather than ESM2015 of `export MyType..;`

### ISSUE THREAD

**Issue by mhevery** [angular/tsickle#848]
Assume following input file: https://github.com/angular/angular/blob/master/packages/core/src/reflection/types.ts

```
export type SetterFn = (obj: any, value: any) => void;
export type GetterFn = (obj: any) => any;
export type MethodFn = (obj: any, args: any[]) => any;
```

The output with Tsickle 0.29.0 was an empty file. This is correct since these types are interfaces are so will never have be referenced from closure type.

The output with Tsickle 0.31.0 is this:
```
/** @typedef {?} */
var SetterFn;
exports.SetterFn = SetterFn;
/** @typedef {?} */
var GetterFn;
exports.GetterFn = GetterFn;
/** @typedef {?} */
var MethodFn;
exports.MethodFn = MethodFn;
```

This is strange for two reasons:
- This is an interface hence we are generating something which would not be needed.
- But MORE IMPORTANTLY the format is in common.js format rather than ESM2015 which is what the rest of the files are.

The above code confuses closure compile which fails with this error:

```
java.lang.NullPointerException: NAME ɵangular_packages_common_common_e 6795 [length: 33] [originalname: ɵangular_packages_common_common_e] [source_file: node_modules/@angular/common/fesm2015/common.js]
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:799)
        at com.google.javascript.jscomp.RemoveUnusedCode.getVarForNameNode(RemoveUnusedCode.java:667)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNameNode(RemoveUnusedCode.java:529)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:404)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1116)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:413)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1116)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:413)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1116)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:413)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1116)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:339)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1116)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:413)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1116)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:413)
        at com.google.javascript.jscomp.RemoveUnusedCode.access$1200(RemoveUnusedCode.java:90)
        at com.google.javascript.jscomp.RemoveUnusedCode$Continuation.apply(RemoveUnusedCode.java:1534)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseAndRemoveUnusedReferences(RemoveUnusedCode.java:247)
        at com.google.javascript.jscomp.RemoveUnusedCode.process(RemoveUnusedCode.java:228)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:303)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
        at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2541)
        at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:834)
        at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:830)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:101)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by evmar** [comment]
Two things are going on here:

1) We generate the @typedef bits because that is how types look to Closure, and they're needed elsewhere if the code refers to that type.  I think that part is correct.

2) The exports are busted because we thought we were emitting goog.module modules, not ES6 modules.  I completely forgot that we produce ES6 modules.  It might be difficult to produce code that is both valid ES6 and valid goog.module modules, but maybe there's some flag we can key off of.

Relevant code is here:
https://github.com/angular/tsickle/blob/5474fb7b3439f93a7a48123fa2e996828b70512b/src/tsickle.ts#L1111

**Comment by evmar** [comment]
If you search tsickle.ts for the string `exports.` you'll find a bunch of places where it attempts to emit things in that manner.  I'm a little surprised this didn't break earlier.

**Comment by evmar** [comment]
I think this is actually the offending code.  I wonder if it'd be safe to emit an 'export {}' here.  I'll try it.
https://github.com/angular/tsickle/blob/master/src/tsickle.ts#L1467
