### ISSUE TITLE
AssertionError: absolute path expected

### ISSUE THREAD

**Issue by kemsky** [angular/tsickle#930]
angular 7.0.1
tsickle 0.33.1

```json
  "angularCompilerOptions": {
    ...
    "outDir": "Spa_Output/ngc",
    ...
  }
```

```
[10:17:04]	[Step 4/16] [10:17:04] Command: node.exe --max-old-space-size=4096 C:\TeamCity\buildAgent\work\b682337d00addb49\<Application>\node_modules\@angular\compiler-cli\src\main.js -p tsconfig-aot.json
[10:17:25]	[Step 4/16] [10:17:25] : AssertionError [ERR_ASSERTION]: expected "Spa_Output/ngc/node_modules/@angular/core/core.ngfactory.js.map" to be absolute
[10:17:25]	[Step 4/16]     at Object.assertAbsolute (C:\TeamCity\buildAgent\work\b682337d00addb49\<Application>\node_modules\tsickle\src\cli_support.js:28:9)
[10:17:25]	[Step 4/16]     at Object.writeFileImpl [as writeFile] (C:\TeamCity\buildAgent\work\b682337d00addb49\<Application>\node_modules\tsickle\src\tsickle.js:140:27)
[10:17:25]	[Step 4/16]     at Object.writeFile (C:\TeamCity\buildAgent\work\b682337d00addb49\<Application>\node_modules\typescript\lib\typescript.js:11087:14)
[10:17:25]	[Step 4/16]     at printSourceFileOrBundle (C:\TeamCity\buildAgent\work\b682337d00addb49\<Application>\node_modules\typescript\lib\typescript.js:80570:20)
[10:17:25]	[Step 4/16]     at emitJsFileOrBundle (C:\TeamCity\buildAgent\work\b682337d00addb49\<Application>\node_modules\typescript\lib\typescript.js:80491:13)
[10:17:25]	[Step 4/16]     at emitSourceFileOrBundle (C:\TeamCity\buildAgent\work\b682337d00addb49\<Application>\node_modules\typescript\lib\typescript.js:80448:13)
[10:17:25]	[Step 4/16]     at forEachEmittedFile (C:\TeamCity\buildAgent\work\b682337d00addb49\<Application>\node_modules\typescript\lib\typescript.js:80355:30)
[10:17:25]	[Step 4/16]     at Object.emitFiles (C:\TeamCity\buildAgent\work\b682337d00addb49\<Application>\node_modules\typescript\lib\typescript.js:80437:9)
[10:17:25]	[Step 4/16]     at emitWorker (C:\TeamCity\buildAgent\work\b682337d00addb49\<Application>\node_modules\typescript\lib\typescript.js:85138:33)
[10:17:25]	[Step 4/16]     at C:\TeamCity\buildAgent\work\b682337d00addb49\<Application>\node_modules\typescript\lib\typescript.js:85098:66
```

**Comment by evmar** [comment]
@alexeagle I think this is caused by angular loading the tsconfig wrong.  Somewhere around here:
https://github.com/angular/angular/blob/master/packages/compiler-cli/src/perform_compile.ts#L129

The TS APIs expect to be called with absolute paths, but it's up to the caller to make them absolute.

**Comment by evmar** [comment]
Also I could "fix" this by removing this check in tsickle but this is revealing a code path that will likely do the wrong thing later.

**Comment by evmar** [comment]
This is an Angular bug, so I think there's nothing for us to do.
